spring.application.name=chatroom

#SQL Server
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=chat_room;encrypt=true;trustServerCertificate=true
#spring.datasource.username=danny666
#spring.datasource.password=Aa12345!
#spring.jpa.hibernate.ddl-auto=validate

#H2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:chat_room;MODE=MSSQLServer;DATABASE_TO_UPPER=false
spring.datasource.username=sa
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console